
export interface GrammarSentence {
    id: string;
    level: string;
    sentence: string;
    translation: string;
    topic?: string;
}

export const GRAMMAR_SENTENCES_A1: GrammarSentence[] = [
    { id: 'g-a1-01', level: 'A1', sentence: "I am a student at this university.", translation: "Tôi là sinh viên tại trường đại học này." },
    { id: 'g-a1-02', level: 'A1', sentence: "She is from Vietnam.", translation: "Cô ấy đến từ Việt Nam." },
    { id: 'g-a1-03', level: 'A1', sentence: "They are not happy about the news.", translation: "Họ không vui về tin tức này." },
    { id: 'g-a1-04', level: 'A1', sentence: "Do you like to play football?", translation: "Bạn có thích chơi bóng đá không?" },
    { id: 'g-a1-05', level: 'A1', sentence: "He gets up at six o'clock every day.", translation: "Anh ấy thức dậy lúc 6 giờ mỗi ngày." },
    { id: 'g-a1-06', level: 'A1', sentence: "Where is the nearest supermarket?", translation: "Siêu thị gần nhất ở đâu?" },
    { id: 'g-a1-07', level: 'A1', sentence: "There is a book on the table.", translation: "Có một cuốn sách trên bàn." },
    { id: 'g-a1-08', level: 'A1', sentence: "We do not have enough money.", translation: "Chúng tôi không có đủ tiền." },
    { id: 'g-a1-09', level: 'A1', sentence: "My brother works in a bank.", translation: "Anh trai tôi làm việc trong một ngân hàng." },
    { id: 'g-a1-10', level: 'A1', sentence: "Can you help me with this?", translation: "Bạn có thể giúp tôi việc này không?" },
    { id: 'g-a1-11', level: 'A1', sentence: "It is raining right now.", translation: "Trời đang mưa ngay lúc này." },
    { id: 'g-a1-12', level: 'A1', sentence: "I usually go to school by bus.", translation: "Tôi thường đi học bằng xe buýt." },
    { id: 'g-a1-13', level: 'A1', sentence: "My favorite color is blue.", translation: "Màu yêu thích của tôi là màu xanh dương." },
    { id: 'g-a1-14', level: 'A1', sentence: "She has long black hair.", translation: "Cô ấy có mái tóc đen dài." },
    { id: 'g-a1-15', level: 'A1', sentence: "We are very hungry.", translation: "Chúng tôi đang rất đói." },
    { id: 'g-a1-16', level: 'A1', sentence: "This is my new computer.", translation: "Đây là máy tính mới của tôi." },
    { id: 'g-a1-17', level: 'A1', sentence: "How old are you?", translation: "Bạn bao nhiêu tuổi?" },
    { id: 'g-a1-18', level: 'A1', sentence: "He does not like coffee.", translation: "Anh ấy không thích cà phê." },
    { id: 'g-a1-19', level: 'A1', sentence: "They play football on Sundays.", translation: "Họ chơi bóng đá vào các ngày Chủ nhật." },
    { id: 'g-a1-20', level: 'A1', sentence: "Please close the door.", translation: "Làm ơn hãy đóng cửa lại." },
    { id: 'g-a1-21', level: 'A1', sentence: "I can speak a little English.", translation: "Tôi có thể nói một chút tiếng Anh." },
    { id: 'g-a1-22', level: 'A1', sentence: "Her birthday is in May.", translation: "Sinh nhật của cô ấy vào tháng Năm." },
    { id: 'g-a1-23', level: 'A1', sentence: "Look at that beautiful bird!", translation: "Nhìn con chim xinh đẹp kia kìa!" },
    { id: 'g-a1-24', level: 'A1', sentence: "Is there a bank near here?", translation: "Có ngân hàng nào gần đây không?" },
    { id: 'g-a1-25', level: 'A1', sentence: "My father is a doctor.", translation: "Bố tôi là một bác sĩ." },
    { id: 'g-a1-26', level: 'A1', sentence: "We watch TV in the evening.", translation: "Chúng tôi xem TV vào buổi tối." },
    { id: 'g-a1-27', level: 'A1', sentence: "Why are you sad?", translation: "Tại sao bạn buồn?" },
    { id: 'g-a1-28', level: 'A1', sentence: "These shoes are very comfortable.", translation: "Đôi giày này rất thoải mái." },
    { id: 'g-a1-29', level: 'A1', sentence: "I want to buy a ticket.", translation: "Tôi muốn mua một chiếc vé." },
    { id: 'g-a1-30', level: 'A1', sentence: "It is sunny today.", translation: "Hôm nay trời nắng." },
    { id: 'g-a1-31', level: 'A1', sentence: "Do not touch that.", translation: "Đừng chạm vào cái đó." },
    { id: 'g-a1-32', level: 'A1', sentence: "She listens to music every night.", translation: "Cô ấy nghe nhạc mỗi tối." }
];

export const GRAMMAR_SENTENCES_A2: GrammarSentence[] = [
    { id: 'g-a2-01', level: 'A2', sentence: "I went to the cinema yesterday.", translation: "Tôi đã đi xem phim ngày hôm qua." },
    { id: 'g-a2-02', level: 'A2', sentence: "Did you enjoy the party last night?", translation: "Bạn có thích bữa tiệc tối qua không?" },
    { id: 'g-a2-03', level: 'A2', sentence: "She was cooking when I came home.", translation: "Cô ấy đang nấu ăn khi tôi về nhà." },
    { id: 'g-a2-04', level: 'A2', sentence: "I am going to visit my grandparents next week.", translation: "Tôi dự định sẽ thăm ông bà vào tuần tới." },
    { id: 'g-a2-05', level: 'A2', sentence: "This car is more expensive than that one.", translation: "Chiếc xe này đắt hơn chiếc kia." },
    { id: 'g-a2-06', level: 'A2', sentence: "He is the tallest student in the class.", translation: "Anh ấy là học sinh cao nhất trong lớp." },
    { id: 'g-a2-07', level: 'A2', sentence: "You should see a doctor.", translation: "Bạn nên đi gặp bác sĩ." },
    { id: 'g-a2-08', level: 'A2', sentence: "Have you ever been to Paris?", translation: "Bạn đã bao giờ đến Paris chưa?" },
    { id: 'g-a2-09', level: 'A2', sentence: "I have lived here for five years.", translation: "Tôi đã sống ở đây được năm năm." },
    { id: 'g-a2-10', level: 'A2', sentence: "While I was studying, my phone rang.", translation: "Khi tôi đang học, điện thoại của tôi reo." },
    { id: 'g-a2-11', level: 'A2', sentence: "I will call you when I arrive.", translation: "Tôi sẽ gọi cho bạn khi tôi đến nơi." },
    { id: 'g-a2-12', level: 'A2', sentence: "She sings better than me.", translation: "Cô ấy hát hay hơn tôi." },
    { id: 'g-a2-13', level: 'A2', sentence: "We have to wear a uniform at work.", translation: "Chúng tôi phải mặc đồng phục tại nơi làm việc." },
    { id: 'g-a2-14', level: 'A2', sentence: "I haven't seen him since Monday.", translation: "Tôi đã không gặp anh ấy từ thứ Hai." },
    { id: 'g-a2-15', level: 'A2', sentence: "Could you please pass the salt?", translation: "Bạn có thể vui lòng đưa giúp tôi lọ muối không?" },
    { id: 'g-a2-16', level: 'A2', sentence: "While they were playing, it started to rain.", translation: "Khi họ đang chơi thì trời bắt đầu mưa." },
    { id: 'g-a2-17', level: 'A2', sentence: "This is the most interesting book I own.", translation: "Đây là cuốn sách thú vị nhất mà tôi sở hữu." },
    { id: 'g-a2-18', level: 'A2', sentence: "Nobody knows the answer.", translation: "Không ai biết câu trả lời." },
    { id: 'g-a2-19', level: 'A2', sentence: "I am going to buy a new laptop tomorrow.", translation: "Tôi dự định sẽ mua một chiếc laptop mới vào ngày mai." },
    { id: 'g-a2-20', level: 'A2', sentence: "He was too tired to finish the work.", translation: "Anh ấy đã quá mệt để hoàn thành công việc." },
    { id: 'g-a2-21', level: 'A2', sentence: "If it rains, we will stay at home.", translation: "Nếu trời mưa, chúng tôi sẽ ở nhà." },
    { id: 'g-a2-22', level: 'A2', sentence: "Have you finished your homework yet?", translation: "Bạn đã làm xong bài tập về nhà chưa?" },
    { id: 'g-a2-23', level: 'A2', sentence: "She told me to wait here.", translation: "Cô ấy bảo tôi đợi ở đây." },
    { id: 'g-a2-24', level: 'A2', sentence: "My car is being repaired.", translation: "Xe của tôi đang được sửa chữa." },
    { id: 'g-a2-25', level: 'A2', sentence: "I used to ride a bike to school.", translation: "Tôi đã từng đạp xe đi học." },
    { id: 'g-a2-26', level: 'A2', sentence: "There are not many people in the park.", translation: "Không có nhiều người trong công viên." },
    { id: 'g-a2-27', level: 'A2', sentence: "Do you know how to swim?", translation: "Bạn có biết bơi không?" },
    { id: 'g-a2-28', level: 'A2', sentence: "Let's go for a walk.", translation: "Chúng ta hãy đi dạo nhé." },
    { id: 'g-a2-29', level: 'A2', sentence: "He works harder than his brother.", translation: "Anh ấy làm việc chăm chỉ hơn anh trai mình." },
    { id: 'g-a2-30', level: 'A2', sentence: "I was born in 1999.", translation: "Tôi sinh năm 1999." }
];

export const GRAMMAR_SENTENCES_B1: GrammarSentence[] = [
    { id: 'g-b1-01', level: 'B1', sentence: "If I study hard, I will pass the exam.", translation: "Nếu tôi học chăm chỉ, tôi sẽ đỗ kỳ thi." },
    { id: 'g-b1-02', level: 'B1', sentence: "The book which I bought yesterday is very interesting.", translation: "Cuốn sách tôi mua hôm qua rất thú vị." },
    { id: 'g-b1-03', level: 'B1', sentence: "I used to play tennis when I was a child.", translation: "Tôi thường chơi tennis khi tôi còn nhỏ." },
    { id: 'g-b1-04', level: 'B1', sentence: "She asked me where I lived.", translation: "Cô ấy hỏi tôi sống ở đâu." },
    { id: 'g-b1-05', level: 'B1', sentence: "The house was built in 1990.", translation: "Ngôi nhà được xây dựng vào năm 1990." },
    { id: 'g-b1-06', level: 'B1', sentence: "I look forward to hearing from you soon.", translation: "Tôi mong sớm nhận được tin từ bạn." },
    { id: 'g-b1-07', level: 'B1', sentence: "You must not smoke in this area.", translation: "Bạn không được phép hút thuốc trong khu vực này." },
    { id: 'g-b1-08', level: 'B1', sentence: "I have been waiting for you since 2 PM.", translation: "Tôi đã đợi bạn từ 2 giờ chiều." },
    { id: 'g-b1-09', level: 'B1', sentence: "Unless you hurry, you will miss the bus.", translation: "Trừ khi bạn nhanh lên, bạn sẽ lỡ xe buýt." },
    { id: 'g-b1-10', level: 'B1', sentence: "It is too expensive for me to buy.", translation: "Nó quá đắt để tôi có thể mua." },
    { id: 'g-b1-11', level: 'B1', sentence: "I would buy a car if I had enough money.", translation: "Tôi sẽ mua ô tô nếu tôi có đủ tiền." },
    { id: 'g-b1-12', level: 'B1', sentence: "The man who is standing there is my uncle.", translation: "Người đàn ông đang đứng kia là chú của tôi." },
    { id: 'g-b1-13', level: 'B1', sentence: "She is capable of solving complex problems.", translation: "Cô ấy có khả năng giải quyết các vấn đề phức tạp." },
    { id: 'g-b1-14', level: 'B1', sentence: "I regret telling him the secret.", translation: "Tôi hối hận vì đã nói cho anh ấy bí mật đó." },
    { id: 'g-b1-15', level: 'B1', sentence: "The meeting has been cancelled.", translation: "Cuộc họp đã bị hủy bỏ." },
    { id: 'g-b1-16', level: 'B1', sentence: "Despite working hard, he didn't get a promotion.", translation: "Mặc dù làm việc chăm chỉ, anh ấy vẫn không được thăng chức." },
    { id: 'g-b1-17', level: 'B1', sentence: "You had better leave now.", translation: "Tốt hơn là bạn nên rời đi ngay bây giờ." },
    { id: 'g-b1-18', level: 'B1', sentence: "It takes me 30 minutes to get to work.", translation: "Tôi mất 30 phút để đi làm." },
    { id: 'g-b1-19', level: 'B1', sentence: "I wish I knew how to play the piano.", translation: "Tôi ước tôi biết chơi piano." },
    { id: 'g-b1-20', level: 'B1', sentence: "She asked if I had seen her keys.", translation: "Cô ấy hỏi tôi có thấy chìa khóa của cô ấy không." },
    { id: 'g-b1-21', level: 'B1', sentence: "By the time we arrived, the film had started.", translation: "Vào lúc chúng tôi đến, bộ phim đã bắt đầu rồi." },
    { id: 'g-b1-22', level: 'B1', sentence: "He is interested in learning Japanese.", translation: "Anh ấy hứng thú với việc học tiếng Nhật." },
    { id: 'g-b1-23', level: 'B1', sentence: "I would rather stay home tonight.", translation: "Tôi thà ở nhà tối nay." },
    { id: 'g-b1-24', level: 'B1', sentence: "Stop making that noise!", translation: "Ngừng gây ồn ào đi!" },
    { id: 'g-b1-25', level: 'B1', sentence: "Neither Mark nor his friends are coming.", translation: "Cả Mark và bạn của anh ấy đều không đến." },
    { id: 'g-b1-26', level: 'B1', sentence: "The tea is too hot to drink.", translation: "Trà quá nóng để uống." },
    { id: 'g-b1-27', level: 'B1', sentence: "Have you had your hair cut?", translation: "Bạn vừa mới cắt tóc à?" },
    { id: 'g-b1-28', level: 'B1', sentence: "I promise I will not be late.", translation: "Tôi hứa tôi sẽ không đến muộn." },
    { id: 'g-b1-29', level: 'B1', sentence: "They are expected to arrive soon.", translation: "Họ được mong đợi sẽ đến sớm." },
    { id: 'g-b1-30', level: 'B1', sentence: "You need not bring any food.", translation: "Bạn không cần mang theo thức ăn đâu." }
];

export const GRAMMAR_SENTENCES_B2: GrammarSentence[] = [
    { id: 'g-b2-01', level: 'B2', sentence: "Had I known about the traffic, I would have left earlier.", translation: "Nếu tôi biết về giao thông, tôi đã rời đi sớm hơn." },
    { id: 'g-b2-02', level: 'B2', sentence: "Not only is he intelligent, but he is also very funny.", translation: "Không chỉ thông minh, anh ấy còn rất hài hước." },
    { id: 'g-b2-03', level: 'B2', sentence: "I would rather you did not smoke here.", translation: "Tôi thà bạn đừng hút thuốc ở đây." },
    { id: 'g-b2-04', level: 'B2', sentence: "Despite the rain, we enjoyed the concert.", translation: "Mặc dù trời mưa, chúng tôi vẫn thích buổi hòa nhạc." },
    { id: 'g-b2-05', level: 'B2', sentence: "It is high time we started working on the project.", translation: "Đã đến lúc chúng ta bắt đầu làm việc vào dự án." },
    { id: 'g-b2-06', level: 'B2', sentence: "I suggest that she apply for the job.", translation: "Tôi gợi ý cô ấy nên ứng tuyển công việc đó." },
    { id: 'g-b2-07', level: 'B2', sentence: "No sooner had I arrived than the meeting started.", translation: "Ngay khi tôi vừa đến thì cuộc họp bắt đầu." },
    { id: 'g-b2-08', level: 'B2', sentence: "Under no circumstances should you open this door.", translation: "Trong bất kỳ hoàn cảnh nào bạn cũng không được mở cửa này." },
    { id: 'g-b2-09', level: 'B2', sentence: "Suppose you lost your job, what would you do?", translation: "Giả sử bạn mất việc, bạn sẽ làm gì?" },
    { id: 'g-b2-10', level: 'B2', sentence: "He is used to waking up early.", translation: "Anh ấy đã quen với việc thức dậy sớm." },
    { id: 'g-b2-11', level: 'B2', sentence: "I will have finished the report by Friday.", translation: "Tôi sẽ hoàn thành báo cáo trước thứ Sáu." },
    { id: 'g-b2-12', level: 'B2', sentence: "The reason why he left is still unknown.", translation: "Lý do anh ấy rời đi vẫn chưa được biết." },
    { id: 'g-b2-13', level: 'B2', sentence: "It was such a boring movie that I fell asleep.", translation: "Bộ phim chán đến nỗi tôi đã ngủ gật." },
    { id: 'g-b2-14', level: 'B2', sentence: "Only when I read the letter did I understand.", translation: "Chỉ khi tôi đọc lá thư tôi mới hiểu." },
    { id: 'g-b2-15', level: 'B2', sentence: "You might have left your phone in the car.", translation: "Có thể bạn đã để quên điện thoại trong xe." },
    { id: 'g-b2-16', level: 'B2', sentence: "Regardless of the cost, we must save him.", translation: "Bất kể chi phí thế nào, chúng ta phải cứu anh ấy." },
    { id: 'g-b2-17', level: 'B2', sentence: "If only I had studied harder for the test.", translation: "Giá như tôi đã học chăm hơn cho bài kiểm tra." },
    { id: 'g-b2-18', level: 'B2', sentence: "She objected to being treated like a child.", translation: "Cô ấy phản đối việc bị đối xử như một đứa trẻ." },
    { id: 'g-b2-19', level: 'B2', sentence: "Having finished his work, he went home.", translation: "Sau khi hoàn thành công việc, anh ấy về nhà." },
    { id: 'g-b2-20', level: 'B2', sentence: "The more you practice, the better you become.", translation: "Bạn càng luyện tập, bạn càng trở nên giỏi hơn." },
    { id: 'g-b2-21', level: 'B2', sentence: "It is believed that the thief escaped by boat.", translation: "Người ta tin rằng tên trộm đã trốn thoát bằng thuyền." },
    { id: 'g-b2-22', level: 'B2', sentence: "Keep an eye on my bag while I am away.", translation: "Để mắt đến túi của tôi khi tôi đi vắng nhé." },
    { id: 'g-b2-23', level: 'B2', sentence: "Unless I am mistaken, that is John's car.", translation: "Trừ khi tôi nhầm, đó là xe của John." },
    { id: 'g-b2-24', level: 'B2', sentence: "We prevented them from entering the building.", translation: "Chúng tôi đã ngăn họ vào tòa nhà." },
    { id: 'g-b2-25', level: 'B2', sentence: "There is no point in arguing with him.", translation: "Tranh cãi với anh ấy chẳng có ích gì đâu." },
    { id: 'g-b2-26', level: 'B2', sentence: "I would sooner you didn't tell anyone.", translation: "Tôi thà bạn đừng nói với ai cả." },
    { id: 'g-b2-27', level: 'B2', sentence: "She is on the verge of crying.", translation: "Cô ấy sắp khóc rồi." },
    { id: 'g-b2-28', level: 'B2', sentence: "It goes without saying that health is important.", translation: "Không cần phải nói cũng biết sức khỏe là quan trọng." }
];

export const GRAMMAR_SENTENCES_C1: GrammarSentence[] = [
    { id: 'g-c1-01', level: 'C1', sentence: "Little did I know that he was the CEO.", translation: "Tôi không hề biết rằng anh ấy là CEO." },
    { id: 'g-c1-02', level: 'C1', sentence: "Were it not for your help, I would have failed.", translation: "Nếu không có sự giúp đỡ của bạn, tôi đã thất bại." },
    { id: 'g-c1-03', level: 'C1', sentence: "He is believed to have committed the crime.", translation: "Anh ấy được cho là đã phạm tội." },
    { id: 'g-c1-04', level: 'C1', sentence: "It is crucial that he remain silent.", translation: "Điều quan trọng là anh ấy phải giữ im lặng." },
    { id: 'g-c1-05', level: 'C1', sentence: "Seldom have I seen such a beautiful sunset.", translation: "Hiếm khi tôi thấy một hoàng hôn đẹp như vậy." },
    { id: 'g-c1-06', level: 'C1', sentence: "Hardly had I sat down when the phone rang.", translation: "Tôi vừa mới ngồi xuống thì điện thoại reo." },
    { id: 'g-c1-07', level: 'C1', sentence: "Not until the next day did I realize my mistake.", translation: "Mãi đến ngày hôm sau tôi mới nhận ra sai lầm của mình." },
    { id: 'g-c1-08', level: 'C1', sentence: "In no way am I responsible for this mess.", translation: "Không đời nào tôi chịu trách nhiệm cho mớ hỗn độn này." },
    { id: 'g-c1-09', level: 'C1', sentence: "Should you need any assistance, please let us know.", translation: "Nếu bạn cần bất kỳ sự hỗ trợ nào, vui lòng cho chúng tôi biết." },
    { id: 'g-c1-10', level: 'C1', sentence: "I would have visited you, but I was tied up with work.", translation: "Tôi đã định ghé thăm bạn, nhưng tôi lại bị kẹt công việc." },
    { id: 'g-c1-11', level: 'C1', sentence: "He speaks not only English but also French fluently.", translation: "Anh ấy không chỉ nói tiếng Anh mà còn nói tiếng Pháp trôi chảy." },
    { id: 'g-c1-12', level: 'C1', sentence: "It was not until 1995 that the war ended.", translation: "Mãi đến năm 1995 chiến tranh mới kết thúc." },
    { id: 'g-c1-13', level: 'C1', sentence: "Given the circumstances, we have done a good job.", translation: "Xét trong hoàn cảnh đó, chúng ta đã làm tốt." },
    { id: 'g-c1-14', level: 'C1', sentence: "So angry was she that she couldn't speak.", translation: "Cô ấy giận đến mức không nói nên lời." },
    { id: 'g-c1-15', level: 'C1', sentence: "Whatever the outcome, I will accept it.", translation: "Dù kết quả thế nào, tôi cũng sẽ chấp nhận." },
    { id: 'g-c1-16', level: 'C1', sentence: "Much as I respect him, I cannot agree with his methods.", translation: "Dù tôi tôn trọng anh ấy nhiều, tôi không thể đồng ý với phương pháp của anh ấy." },
    { id: 'g-c1-17', level: 'C1', sentence: "Try as he might, he could not open the jar.", translation: "Dù anh ấy đã cố gắng hết sức, anh ấy vẫn không mở được cái lọ." },
    { id: 'g-c1-18', level: 'C1', sentence: "Had it not been for the alarm, I would have overslept.", translation: "Nếu không có báo thức, tôi đã ngủ quên rồi." },
    { id: 'g-c1-19', level: 'C1', sentence: "I was under the impression that the meeting was tomorrow.", translation: "Tôi cứ tưởng rằng cuộc họp là vào ngày mai." },
    { id: 'g-c1-20', level: 'C1', sentence: "On no account must this switch be touched.", translation: "Không vì lý do gì được chạm vào công tắc này." },
    { id: 'g-c1-21', level: 'C1', sentence: "Rarely does a week pass without him calling his mother.", translation: "Hiếm khi có tuần nào trôi qua mà anh ấy không gọi cho mẹ." },
    { id: 'g-c1-22', level: 'C1', sentence: "Whether or not you like it, we are moving.", translation: "Dù bạn thích hay không, chúng ta vẫn sẽ chuyển đi." },
    { id: 'g-c1-23', level: 'C1', sentence: "To be honest, I am having second thoughts.", translation: "Thành thật mà nói, tôi đang suy nghĩ lại." },
    { id: 'g-c1-24', level: 'C1', sentence: "It stands to reason that they would decline the offer.", translation: "Việc họ từ chối lời đề nghị là điều hiển nhiên." },
    { id: 'g-c1-25', level: 'C1', sentence: "We must ensure that the rules are complied with.", translation: "Chúng ta phải đảm bảo rằng các quy tắc được tuân thủ." }
];

export const GRAMMAR_SENTENCES_C2: GrammarSentence[] = [
    { id: 'g-c2-01', level: 'C2', sentence: "Be that as it may, I still disagree with your decision.", translation: "Dù vậy, tôi vẫn không đồng ý với quyết định của bạn." },
    { id: 'g-c2-02', level: 'C2', sentence: "Scarcely had the plane taken off when the engine failed.", translation: "Máy bay vừa mới cất cánh thì động cơ bị hỏng." },
    { id: 'g-c2-03', level: 'C2', sentence: "However hard he tried, he could not succeed.", translation: "Dù anh ấy đã cố gắng thế nào, anh ấy cũng không thể thành công." },
    { id: 'g-c2-04', level: 'C2', sentence: "Such was the force of the storm that trees were uprooted.", translation: "Cơn bão mạnh đến nỗi cây cối bị nhổ bật rễ." },
    { id: 'g-c2-05', level: 'C2', sentence: "I take great exception to that remark.", translation: "Tôi phản đối mạnh mẽ nhận xét đó." },
    { id: 'g-c2-06', level: 'C2', sentence: "The plan is subject to approval by the board.", translation: "Kế hoạch này phải được hội đồng phê duyệt." },
    { id: 'g-c2-07', level: 'C2', sentence: "She has a propensity for exaggeration.", translation: "Cô ấy có thiên hướng hay phóng đại." },
    { id: 'g-c2-08', level: 'C2', sentence: "Notwithstanding the financial difficulties, the project continued.", translation: "Bất chấp những khó khăn tài chính, dự án vẫn tiếp tục." },
    { id: 'g-c2-09', level: 'C2', sentence: "He was completely taken aback by the news.", translation: "Anh ấy hoàn toàn ngạc nhiên trước tin tức này." },
    { id: 'g-c2-10', level: 'C2', sentence: "Assuming that to be true, what are our options?", translation: "Giả sử điều đó là đúng, chúng ta có những lựa chọn nào?" },
    { id: 'g-c2-11', level: 'C2', sentence: "By no means is this the only solution.", translation: "Đây tuyệt nhiên không phải là giải pháp duy nhất." },
    { id: 'g-c2-12', level: 'C2', sentence: "Never before has there been such a demand for electric cars.", translation: "Chưa bao giờ nhu cầu xe điện lại lớn như vậy." },
    { id: 'g-c2-13', level: 'C2', sentence: "The Prime Minister is to visit the hospital today.", translation: "Thủ tướng dự kiến sẽ thăm bệnh viện hôm nay." },
    { id: 'g-c2-14', level: 'C2', sentence: "But for his lack of experience, he would have got the job.", translation: "Nếu không vì thiếu kinh nghiệm, anh ấy đã nhận được công việc rồi." },
    { id: 'g-c2-15', level: 'C2', sentence: "We are committed to seeing this through to the end.", translation: "Chúng tôi cam kết sẽ theo đuổi việc này đến cùng." },
    { id: 'g-c2-16', level: 'C2', sentence: "There is a high probability that prices will rise.", translation: "Có khả năng cao là giá cả sẽ tăng." },
    { id: 'g-c2-17', level: 'C2', sentence: "It is imperative that appropriate action be taken.", translation: "Bắt buộc phải có hành động thích hợp được thực hiện." },
    { id: 'g-c2-18', level: 'C2', sentence: "Lest you forget, the deadline is tomorrow.", translation: "Kẻo bạn quên, hạn chót là ngày mai đấy." },
    { id: 'g-c2-19', level: 'C2', sentence: "Suffice it to say, we were disappointed.", translation: "Chỉ cần nói rằng chúng tôi đã thất vọng là đủ." },
    { id: 'g-c2-20', level: 'C2', sentence: "In the event of fire, press the alarm button.", translation: "Trong trường hợp hỏa hoạn, hãy nhấn nút báo động." },
    { id: 'g-c2-21', level: 'C2', sentence: "He acted as if he had never met her.", translation: "Anh ấy hành động như thể anh ấy chưa bao giờ gặp cô ấy." },
    { id: 'g-c2-22', level: 'C2', sentence: "The sheer magnitude of the task overwhelmed him.", translation: "Mức độ lớn lao của nhiệm vụ đã làm anh ấy choáng ngợp." },
    { id: 'g-c2-23', level: 'C2', sentence: "Were it not for your diligence, we would have failed.", translation: "Nếu không nhờ sự cần cù của bạn, chúng ta đã thất bại." }
];
